awk '
/Logout Active Driver button/ {
    print "        // Card: Driver Profile & Selfie Photo (Read-only profile summary)"
    print "        Card("
    print "            colors = CardDefaults.cardColors(containerColor = TaxiWhite),"
    print "            shape = RoundedCornerShape(24.dp),"
    print "            border = BorderStroke(1.dp, Slate200),"
    print "            elevation = CardDefaults.cardElevation(defaultElevation = 0.dp),"
    print "            modifier = Modifier.fillMaxWidth()"
    print "        ) {"
    print "            Column("
    print "                modifier = Modifier.padding(24.dp),"
    print "                verticalArrangement = Arrangement.spacedBy(16.dp)"
    print "            ) {"
    print "                Row("
    print "                    modifier = Modifier.fillMaxWidth(),"
    print "                    horizontalArrangement = Arrangement.SpaceBetween,"
    print "                    verticalAlignment = Alignment.CenterVertically"
    print "                ) {"
    print "                    Text("
    print "                        text = \"DRIVER PROFILE & SELFIE PHOTO\","
    print "                        fontSize = 11.sp,"
    print "                        fontWeight = FontWeight.Bold,"
    print "                        color = TaxiBlack,"
    print "                        letterSpacing = 1.sp"
    print "                    )"
    print "                }"
    print ""
    print "                // READ-ONLY DISPLAY VIEW"
    print "                Row("
    print "                    modifier = Modifier.fillMaxWidth(),"
    print "                    verticalAlignment = Alignment.CenterVertically"
    print "                ) {"
    print "                    val selfieBitmap = remember(sDriverSelfiePath) {"
    print "                        if (sDriverSelfiePath.isNotEmpty()) {"
    print "                            try {"
    print "                                BitmapFactory.decodeFile(sDriverSelfiePath)?.asImageBitmap()"
    print "                            } catch (e: Exception) {"
    print "                                null"
    print "                            }"
    print "                        } else {"
    print "                            null"
    print "                        }"
    print "                    }"
    print ""
    print "                    if (selfieBitmap != null) {"
    print "                        Image("
    print "                            bitmap = selfieBitmap,"
    print "                            contentDescription = \"Driver Photo Settings Preview\","
    print "                            modifier = Modifier"
    print "                                .size(80.dp)"
    print "                                .clip(RoundedCornerShape(16.dp)),"
    print "                            contentScale = ContentScale.Crop"
    print "                        )"
    print "                    } else {"
    print "                        Box("
    print "                            modifier = Modifier"
    print "                                .size(80.dp)"
    print "                                .background(Slate100, RoundedCornerShape(16.dp)),"
    print "                            contentAlignment = Alignment.Center"
    print "                        ) {"
    print "                            Icon("
    print "                                imageVector = Icons.Default.Person,"
    print "                                contentDescription = \"No Photo\","
    print "                                tint = Slate400,"
    print "                                modifier = Modifier.size(32.dp)"
    print "                            )"
    print "                        }"
    print "                    }"
    print ""
    print "                    Spacer(modifier = Modifier.width(16.dp))"
    print ""
    print "                    Column("
    print "                        modifier = Modifier.weight(1f),"
    print "                        verticalArrangement = Arrangement.spacedBy(4.dp)"
    print "                    ) {"
    print "                        Text("
    print "                            text = driverNameVal.ifEmpty { \"No Name Set\" },"
    print "                            fontSize = 18.sp,"
    print "                            fontWeight = FontWeight.Bold,"
    print "                            color = Slate900"
    print "                        )"
    print "                        "
    print "                        Row("
    print "                            verticalAlignment = Alignment.CenterVertically,"
    print "                            horizontalArrangement = Arrangement.spacedBy(4.dp),"
    print "                            modifier = Modifier"
    print "                                .background(Color(0xFFDCFCE7), RoundedCornerShape(8.dp))"
    print "                                .padding(horizontal = 8.dp, vertical = 4.dp)"
    print "                        ) {"
    print "                            Icon("
    print "                                imageVector = Icons.Default.CheckCircle,"
    print "                                contentDescription = \"Verified Driver Badge\","
    print "                                tint = Color(0xFF15803D),"
    print "                                modifier = Modifier.size(14.dp)"
    print "                            )"
    print "                            Text("
    print "                                text = \"TRUSTED & VERIFIED\","
    print "                                fontSize = 10.sp,"
    print "                                fontWeight = FontWeight.Bold,"
    print "                                color = Color(0xFF15803D),"
    print "                                letterSpacing = 0.5.sp"
    print "                            )"
    print "                        }"
    print "                    }"
    print "                }"
    print ""
    print "                HorizontalDivider(color = Slate500.copy(alpha = 0.1f))"
    print ""
    print "                // Vehicle Number & Category Info"
    print "                Row("
    print "                    modifier = Modifier.fillMaxWidth(),"
    print "                    horizontalArrangement = Arrangement.SpaceBetween"
    print "                ) {"
    print "                    Column {"
    print "                        Text("
    print "                            text = \"VEHICLE REGISTRATION NO\","
    print "                            fontSize = 10.sp,"
    print "                            fontWeight = FontWeight.Bold,"
    print "                            color = Slate500,"
    print "                            letterSpacing = 0.5.sp"
    print "                        )"
    print "                        Text("
    print "                            text = vehicleNumVal.ifEmpty { \"N/A\" },"
    print "                            fontSize = 14.sp,"
    print "                            fontWeight = FontWeight.Medium,"
    print "                            color = Slate900"
    print "                        )"
    print "                    }"
    print ""
    print "                    Column(horizontalAlignment = Alignment.End) {"
    print "                        Text("
    print "                            text = \"VEHICLE CATEGORY\","
    print "                            fontSize = 10.sp,"
    print "                            fontWeight = FontWeight.Bold,"
    print "                            color = Slate500,"
    print "                            letterSpacing = 0.5.sp"
    print "                        )"
    print "                        Text("
    print "                            text = vehicleCatVal,"
    print "                            fontSize = 14.sp,"
    print "                            fontWeight = FontWeight.Bold,"
    print "                            color = TaxiBlack"
    print "                        )"
    print "                    }"
    print "                }"
    print "            }"
    print "        }"
    print "        Spacer(modifier = Modifier.height(24.dp))"
    print ""
}
{ print }
' app/src/main/java/com/covaimetertaxi/driver/MainActivity.kt > temp.kt
mv temp.kt app/src/main/java/com/covaimetertaxi/driver/MainActivity.kt
